### ISSUE TITLE
Clarity on image from Android Gallery

### ISSUE THREAD

**Issue by MarkBracey** [TomDannert/Panorama3D#2]
Great Viewer!

I copied the sample images to my Android S6  Photo Album and added code to load those images from the phone into the viewer.

The images loaded from the phone are not as clear, meaning slightly pixelated as compared to those images that I default into the Viewer.

I compared the images on the phone to your samples and they are exactly the same image.

Any ideas on what the difference may be?

**Comment by TomDannert** [comment]
Hallo Mark,

Sorry for my late reply because I was on vacation. I tested the viewer on the iPhone and on my old Samsung galaxy and it was not pixelated. Maybe you lost quality when copying the pictures? It is recommended for the viewer to use high quality images (4k +), as the images are rendered into a squere and the viewer shows only a small section.
